# Generated by Django 3.2.6 on 2021-11-15 19:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('dateTendered', models.DateField(default=datetime.date.today)),
                ('loadNumber', models.CharField(max_length=50)),
                ('masterBolNumber', models.CharField(max_length=50)),
                ('carrier', models.CharField(blank=True, choices=[('GW', 'Greatwide'), ('BL', 'Brian Williams')], default='GW', max_length=100)),
                ('destinationCity', models.CharField(max_length=70)),
                ('destinationState', models.CharField(max_length=50)),
                ('rateLineHaul', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rateFSC', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rateExtras', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('rateTotal', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('loadDelivered', models.BooleanField(default=False)),
                ('customCarrierRate', models.BooleanField(default=False)),
                ('deliveryDate', models.DateField(blank=True, null=True)),
                ('deliveryTime', models.TimeField(blank=True, null=True)),
                ('driverName', models.CharField(blank=True, max_length=70, null=True)),
                ('driverCell', models.CharField(blank=True, max_length=70, null=True)),
                ('rateTotalCarrier', models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True)),
                ('shipmentMargin', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('shipmentMarginPercentage', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('trailerNumber', models.CharField(max_length=200)),
                ('trailerPlateState', models.CharField(max_length=30)),
                ('trailerPlateNumber', models.CharField(max_length=30)),
                ('trailerLeaseCompany', models.CharField(max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripReport',
            fields=[
                ('daysYardEmpToDrayPu', models.IntegerField(blank=True, null=True)),
                ('daysDrayPuToYardLoad', models.IntegerField(blank=True, null=True)),
                ('daysYardLoadToCarrPu', models.IntegerField(blank=True, null=True)),
                ('daysCarrPuToDeliv', models.IntegerField(blank=True, null=True)),
                ('daysDelivToRetEmp', models.IntegerField(blank=True, null=True)),
                ('trailerDaysOwed', models.IntegerField(blank=True, null=True)),
                ('totalDays', models.IntegerField(blank=True, null=True)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('totalTrailerCost', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('grossMargin', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('netMargin', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('netMarginAfterTrailer', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.shipment')),
                ('trailer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.trailer')),
            ],
        ),
        migrations.CreateModel(
            name='TrailerTrip',
            fields=[
                ('dateYardEmpty', models.DateField(blank=True, null=True)),
                ('dateDrayPickedUp', models.DateField(blank=True, null=True)),
                ('dateDrayReturnedLoaded', models.DateField(blank=True, null=True)),
                ('dateCarrierPickedUpLoaded', models.DateField(blank=True, null=True)),
                ('dateCarrierDelivered', models.DateField(blank=True, null=True)),
                ('dateCarrierReturnedEmpty', models.DateField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('shipment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.shipment')),
                ('trailer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.trailer')),
            ],
        ),
        migrations.CreateModel(
            name='TrailerLocation',
            fields=[
                ('locationCity', models.CharField(blank=True, max_length=70, null=True)),
                ('locationState', models.CharField(blank=True, max_length=30, null=True)),
                ('locationCountry', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.CharField(blank=True, max_length=200, null=True)),
                ('longitude', models.CharField(blank=True, max_length=200, null=True)),
                ('statusCode', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('trailer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.trailer')),
            ],
        ),
        migrations.AddField(
            model_name='shipment',
            name='trailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.trailer'),
        ),
    ]
