# Generated by Django 3.2.6 on 2021-11-18 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='trailerNumber',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
