# Generated by Django 3.2.6 on 2021-11-20 22:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_trailer_trailernumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierCharge',
            fields=[
                ('daysOwed', models.IntegerField(blank=True, null=True)),
                ('amountOwed', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('paid', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.shipment')),
                ('tripReport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.tripreport')),
            ],
        ),
    ]
