# Generated by Django 3.2.6 on 2021-11-20 22:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_carriercharge'),
    ]

    operations = [
        migrations.CreateModel(
            name='RheemCharge',
            fields=[
                ('chargeType', models.CharField(blank=True, choices=[('DET', 'Detention'), ('REC', 'Reconsignment'), ('ASST', 'Driver-Assist'), ('TONU', 'TONU'), ('STOR', 'Storage Fee'), ('OTH', 'Other')], default='OTH', max_length=100)),
                ('daysOwed', models.IntegerField(blank=True, null=True)),
                ('amountOwed', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.shipment')),
                ('trailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.trailer')),
            ],
        ),
    ]
